logger:
  format: "text"
  level: "debug"
mongodb:
  uri: "mongodb://mongodb:27017"
  database: "url-shorter"
  collection: "urls"
http-server:
  address: "app"
  port: "8080"
  protocol: "http://"
  read-header-timeout: 4s
  idle-timeout: 60s
cache:
  capacity: 100